"""Vulture whitelist — auto-generated by run_all_checks.py --fix.

Items here are known false positives (interface-mandated params, signal handlers,
context manager protocol params, etc.). Vulture will ignore these.

Regenerate: .venv/bin/python scripts/general_project_maintenance/run_all_checks.py --fix
"""

# Signal handler params (required by signal.signal() callback signature)
signum  # noqa
frame  # noqa

# Context manager __exit__ params (required by protocol)
exc_type  # noqa
exc_val  # noqa
exc_tb  # noqa

# ValidationRunner hook/interface params (used by subclass overrides)
resumed_data  # noqa
resumed_sections  # noqa
checkpoint_name  # noqa
min_quality_score  # noqa

# Function API flags (part of public interface, may not be used internally yet)
require_variational  # noqa
check_gt_coherence  # noqa
