"""Result scanner — discovers and parses all result files into typed objects.

Scans results/experiments/ and results/thesis/ uniformly, classifying
each JSON file by its kind (noiseless pipeline, noisy/ZNE, or experiment).

Fixes applied (2026-05-30):
- Bug #1: Now reports worst-case ΔE/gap across ALL phase4_results points
  (previously only read phase4[0], hiding failures at other h_test values).
- Bug #4: Now parses ALL pipeline_run_*.json files per folder
  (previously only took the latest, missing multi-seed runs in same dir).
- Bug #2: Logs a warning instead of silently defaulting p_layers to 2.
- Skips hidden directories (starting with '.') in recursive scan.
- Handles UnicodeDecodeError in JSON loading.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from project_health.digest.models import (
    CrossTopologyResult,
    ExperimentResult,
    ModeComparisonResult,
    N120SweepResult,
    NoiselessResult,
    NoisyResult,
    ScalingResult,
    compute_verdict,
)
from qmbp_simulation.analysis.metrics import classify_regime

logger = logging.getLogger(__name__)

# Topologies we recognize from folder names
_KNOWN_TOPOLOGIES = ("chain_1d", "heavy_hex", "ladder", "triangular", "kagome", "linnear")
# "linnear" is a typo in the actual folder name (variants_N6_N10_1D_linnear)

# Folders to skip during recursive scanning
_SKIP_FOLDERS = frozenset({"checkpoints", "__pycache__", ".DS_Store"})


class ResultScanner:
    """Scans all result directories and classifies files by kind."""

    # Known test artifact experiment IDs (generated by test_runner_base.py).
    # These are valid test outputs but should NOT appear in analysis reports.
    # NOTE: T1a/T1b/T1c are REAL experiments — test artifacts use "TEST_T1A" etc.
    TEST_ARTIFACT_IDS: set[str] = {
        "TEST",
        "FAIL",
        "XFAIL",
        "NONE",
        "CNT",
    }

    def __init__(self, results_root: Path = Path("results")) -> None:
        self.root = results_root
        self._exclude_tests = False
        self._index: Any = None

    @property
    def index(self):
        """Lazily-initialized ResultIndex for fast experiment discovery."""
        if self._index is None:
            from qmbp_simulation.framework.result_index import ResultIndex
            exp_root = self.root / "experiments"
            self._index = ResultIndex(root=exp_root)
        return self._index

    def scan_all(
        self,
        *,
        exclude_tests: bool = False,
    ) -> tuple[list[NoiselessResult], list[NoisyResult], list[ExperimentResult]]:
        """Scan all result areas and return typed results.

        Parameters
        ----------
        exclude_tests : bool
            If True, filter out known test artifact experiments (T1A, TEST, FAIL, etc.)
            that are generated by test_runner_base.py. Default: False for backward compat.
        """
        self._exclude_tests = exclude_tests
        noiseless: list[NoiselessResult] = []
        noisy: list[NoisyResult] = []
        experiments: list[ExperimentResult] = []

        # Scan results/experiments/
        exp_root = self.root / "experiments"
        if exp_root.exists():
            exp_dirs = [
                d
                for d in sorted(exp_root.iterdir())
                if d.is_dir() and d.name.startswith("exp_") and d.name != "exp_noisy_variants"
            ]
            logger.info("Scanning %d experiment directories...", len(exp_dirs))
            for exp_dir in exp_dirs:
                # Skip directories with empty name after prefix (e.g., "exp_/")
                if exp_dir.name == "exp_":
                    continue
                result = self._parse_experiment_dir(exp_dir)
                if result:
                    # Filter test artifacts if requested
                    if exclude_tests and result.experiment_id in self.TEST_ARTIFACT_IDS:
                        continue
                    # Skip results with empty experiment_id
                    if not result.experiment_id:
                        continue
                    experiments.append(result)
            logger.info("  → %d experiments parsed", len(experiments))

        # Scan results/thesis/
        thesis_root = self.root / "thesis"
        if thesis_root.exists():
            folders = [
                f
                for f in sorted(thesis_root.iterdir())
                if f.is_dir() and not f.name.startswith(".")
            ]
            logger.info("Scanning %d thesis folders...", len(folders))
            for folder in folders:
                context = _infer_topology_from_name(folder.name)
                self._scan_folder_recursive(folder, noiseless, noisy, parent_context=context)
            logger.info("  → %d noiseless, %d noisy results", len(noiseless), len(noisy))

        return noiseless, noisy, experiments

    def scan_folder(
        self, folder_name: str
    ) -> tuple[list[NoiselessResult], list[NoisyResult], list[ExperimentResult]]:
        """Scan a specific folder by name (searches experiments/ then thesis/)."""
        noiseless: list[NoiselessResult] = []
        noisy: list[NoisyResult] = []
        experiments: list[ExperimentResult] = []

        # Try experiments/
        exp_path = self.root / "experiments" / folder_name
        if exp_path.exists() and exp_path.is_dir():
            result = self._parse_experiment_dir(exp_path)
            if result:
                experiments.append(result)
            return noiseless, noisy, experiments

        # Try thesis/ exact match
        thesis_path = self.root / "thesis" / folder_name
        if thesis_path.exists() and thesis_path.is_dir():
            context = _infer_topology_from_name(folder_name)
            self._scan_folder_recursive(thesis_path, noiseless, noisy, parent_context=context)
            return noiseless, noisy, experiments

        # Try thesis/ substring match
        thesis_root = self.root / "thesis"
        if thesis_root.exists():
            for folder in sorted(thesis_root.iterdir()):
                if folder.is_dir() and folder_name.lower() in folder.name.lower():
                    context = _infer_topology_from_name(folder.name)
                    self._scan_folder_recursive(folder, noiseless, noisy, parent_context=context)

        return noiseless, noisy, experiments

    # ── Scaling results ─────────────────────────────────────────────────

    def scan_scaling(self) -> list[ScalingResult]:
        """Scan for MPS scaling validation results.

        Looks for ``scaling_N*_*.json`` files in ``results/scaling/``
        (relative to self.root's parent, since root is usually results/).
        Falls back to ``Path("results/scaling")`` if the primary path
        doesn't exist.

        Returns
        -------
        list[ScalingResult]
            Parsed scaling results, one per JSON file.
        """
        # Primary: self.root / "scaling" (root is usually "results/")
        scaling_dir = self.root / "scaling"
        if not scaling_dir.exists():
            # Fallback: relative to CWD
            scaling_dir = Path("results/scaling")

        if not scaling_dir.exists():
            logger.debug("No scaling results directory found")
            return []

        results: list[ScalingResult] = []
        for path in sorted(scaling_dir.glob("scaling_N*_*.json")):
            parsed = self._parse_scaling_file(path)
            if parsed:
                results.append(parsed)

        logger.info("Scanned %d scaling result files from %s", len(results), scaling_dir)
        return results

    def _parse_scaling_file(self, path: Path) -> ScalingResult | None:
        """Parse a scaling_N*_*.json into a ScalingResult."""
        data = _load_json(path)
        if not data:
            return None

        if data.get("experiment") != "mps_scaling_validation":
            return None

        meta = data.get("metadata", {})
        timing = data.get("timing", {})
        summary = data.get("summary", {})
        vqe_results = data.get("vqe_results", [])

        # Collect per-h metrics from all seed runs
        per_h_de_gap: list[float] = []
        per_h_passed: list[bool] = []
        for seed_run in vqe_results:
            for r in seed_run.get("results", []):
                per_h_de_gap.append(r.get("de_gap", 0.0))
                per_h_passed.append(r.get("passed", False))

        n_pass = summary.get("n_pass", 0)
        n_total = summary.get("n_total", 0)
        all_passed = summary.get("all_passed", False)
        mean_de = float(sum(per_h_de_gap) / max(len(per_h_de_gap), 1))
        max_de = float(max(per_h_de_gap)) if per_h_de_gap else 0.0

        seeds = meta.get("seeds", [42])
        seed = seeds[0] if seeds else 42

        return ScalingResult(
            source_file=str(path),
            folder=path.parent.name,
            n_qubits=meta.get("n", 0),
            p_layers=meta.get("p_layers", 1),
            topology=meta.get("topology", "chain_1d"),
            strategy=meta.get("strategy", "aer_mps"),
            chi_max=meta.get("chi_max", 64),
            precision=meta.get("precision", 0.005),
            seed=seed,
            h_values=meta.get("h_values", []),
            n_pass=n_pass,
            n_total=n_total,
            all_passed=all_passed,
            mean_de_gap=mean_de,
            max_de_gap=max_de,
            phase1_time_s=timing.get("phase1_dmrg_s", 0.0),
            phase2_time_s=timing.get("phase2_vqe_s", 0.0),
            total_time_s=timing.get("total_s", 0.0),
            per_h_de_gap=per_h_de_gap,
            per_h_passed=per_h_passed,
        )

    # ── Mode comparison + N=120 sweep results ─────────────────────────────

    def scan_mode_comparison(self) -> ModeComparisonResult | None:
        """Scan for MPS mode comparison result (deterministic vs stochastic).

        Looks for ``mps_mode_comparison.json`` in ``results/scaling/``.
        """
        scaling_dir = self.root / "scaling"
        if not scaling_dir.exists():
            scaling_dir = Path("results/scaling")
        if not scaling_dir.exists():
            return None

        path = scaling_dir / "mps_mode_comparison.json"
        if not path.exists():
            return None

        data = _load_json(path)
        if not data or data.get("experiment") != "mps_mode_comparison":
            return None

        summary = data.get("summary", {})
        return ModeComparisonResult(
            source_file=str(path),
            results=data.get("results", []),
            all_det_pass=summary.get("all_det_pass", False),
            all_sto_pass=summary.get("all_sto_pass", False),
            mean_speedup=summary.get("mean_speedup", 0.0),
            mean_energy_diff=summary.get("mean_energy_diff", 0.0),
            modes_consistent=summary.get("modes_consistent", False),
        )

    def scan_n120_sweep(self) -> N120SweepResult | None:
        """Scan for N=120 full VQE sweep result.

        Looks for ``scaling_N120_full_sweep.json`` in ``results/scaling/``.
        """
        scaling_dir = self.root / "scaling"
        if not scaling_dir.exists():
            scaling_dir = Path("results/scaling")
        if not scaling_dir.exists():
            return None

        path = scaling_dir / "scaling_N120_full_sweep.json"
        if not path.exists():
            return None

        data = _load_json(path)
        if not data or data.get("experiment") != "N120_full_sweep":
            return None

        summary = data.get("summary", {})
        scaling_law = data.get("scaling_law", {})
        return N120SweepResult(
            source_file=str(path),
            n_qubits=data.get("n_qubits", 120),
            h_min_safe=data.get("h_min_safe", 0.0),
            h_values=data.get("h_values", []),
            seeds=data.get("seeds", []),
            total_time_s=data.get("total_time_s", 0.0),
            n_total=summary.get("n_total", 0),
            n_pass=summary.get("n_pass", 0),
            pass_rate=summary.get("pass_rate", 0.0),
            mean_de_gap=summary.get("mean_de_gap", 0.0),
            max_de_gap=summary.get("max_de_gap", 0.0),
            std_de_gap=summary.get("std_de_gap", 0.0),
            bootstrap_ci_95=summary.get("bootstrap_ci_95_mean_de_gap", []),
            scaling_law_validated=scaling_law.get("validated", False),
        )

    # ── Cross-topology transfer results ──────────────────────────────────

    def scan_cross_topology(self) -> list[CrossTopologyResult]:
        """Scan for cross-topology transfer experiment results.

        Looks for result JSON files in ``results/scaling/cross_topology/``:
        - ``cross_n_validation_*.json``
        - ``cross_topology_transfer_*.json``
        - ``ablation_study_*.json``
        - ``orchestrator_summary_*.json``

        Returns
        -------
        list[CrossTopologyResult]
            Parsed results, one per JSON file.
        """
        cross_topo_dir = self.root / "scaling" / "cross_topology"
        if not cross_topo_dir.exists():
            cross_topo_dir = Path("results/scaling/cross_topology")
        if not cross_topo_dir.exists():
            logger.debug("No cross-topology results directory found")
            return []

        results: list[CrossTopologyResult] = []
        patterns = [
            "cross_n_validation_*.json",
            "cross_topology_transfer_*.json",
            "ablation_study_*.json",
            "orchestrator_summary_*.json",
        ]
        for pattern in patterns:
            for path in sorted(cross_topo_dir.glob(pattern)):
                parsed = self._parse_cross_topology_file(path)
                if parsed:
                    results.append(parsed)

        logger.info("Scanned %d cross-topology results from %s", len(results), cross_topo_dir)
        return results

    def _parse_cross_topology_file(self, path: Path) -> CrossTopologyResult | None:
        """Parse a cross-topology result JSON into a CrossTopologyResult."""
        data = _load_json(path)
        if not data:
            return None

        experiment = data.get("experiment", "")
        meta = data.get("metadata", {})
        data.get("environment", {})
        summary = data.get("summary", data.get("verdict", {}))

        # Determine experiment type from filename or experiment field
        if "cross_n_validation" in path.name or experiment == "cross_n_validation":
            exp_type = "cross_n_validation"
        elif "cross_topology_transfer" in path.name or experiment == "cross_topology_transfer":
            exp_type = "cross_topology_transfer"
        elif "ablation" in path.name or experiment == "ablation_study":
            exp_type = "ablation_study"
        elif "orchestrator" in path.name or experiment == "cross_topology_orchestrator":
            exp_type = "orchestrator_summary"
        else:
            exp_type = experiment or "unknown"

        # Extract common metadata
        seeds = meta.get("seeds", DEFAULT_SEEDS)
        target_n = meta.get("target_n", 10)
        threshold = meta.get("threshold", 0.10)
        norm_type = meta.get("norm_type", "none")
        hidden_dim = meta.get("hidden_dim", 128)
        n_epochs = meta.get("n_epochs", 6000)
        total_time = meta.get("total_time_s", 0.0)
        git_commit = meta.get("git_commit", "")
        timestamp = meta.get("timestamp", "")

        # Extract topology info and metrics based on experiment type
        source_topos: list[str] = []
        target_topos: list[str] = []
        mean_de_gap = 0.0
        std_de_gap = 0.0
        max_de_gap = 0.0
        pass_rate = 0.0
        n_pass = 0
        n_total = 0
        verdict = ""
        all_pass = False
        graph_essential = False
        mlp_gnn_ratio = 0.0
        best_norm = ""
        directions: dict = {}

        if exp_type == "cross_n_validation":
            # Extract from per-topology strategy sections
            topos_tested = summary.get("topologies_tested", [])
            source_topos = topos_tested
            target_topos = topos_tested
            verdict = summary.get("verdict", "")
            all_pass = summary.get("all_topologies_pass", False)
            # Aggregate across strategies
            de_gaps_all = []
            for key, val in data.items():
                if key.startswith("strategy_") and isinstance(val, dict):
                    de_gaps_all.append(val.get("mean_de_gap", 0.0))
            if de_gaps_all:
                mean_de_gap = float(sum(de_gaps_all) / len(de_gaps_all))
                max_de_gap = float(max(de_gaps_all))

        elif exp_type == "cross_topology_transfer":
            cross_topo = data.get("cross_topology", {})
            comparison = data.get("comparison", {})
            for dir_key, agg in cross_topo.items():
                if isinstance(agg, dict) and "mean_de_gap" in agg:
                    directions[dir_key] = agg
                    de_val = agg["mean_de_gap"]
                    if isinstance(de_val, dict):
                        mean_de_gap = max(mean_de_gap, de_val.get("mean", 0.0))
                    else:
                        mean_de_gap = max(mean_de_gap, de_val)
            verdict = comparison.get("verdict", "")
            all_pass = comparison.get("overall_pass", False)
            source_topos = ["triangular", "heavy_hex"]
            target_topos = ["heavy_hex", "triangular"]

        elif exp_type == "ablation_study":
            pred_comp = data.get("predictor_comparison", {})
            data.get("norm_ablation", {})
            verdict_data = data.get("verdict", {})
            # Graph-essential flag
            essential_map = verdict_data.get("graph_structure_essential", {})
            graph_essential = any(essential_map.values()) if essential_map else False
            best_norms = verdict_data.get("best_norm_per_experiment", {})
            if best_norms:
                # Majority norm across experiments
                from collections import Counter

                norm_counts = Counter(best_norms.values())
                best_norm = norm_counts.most_common(1)[0][0] if norm_counts else ""
            # Extract GNN metrics from first predictor comparison
            for _exp_label, comp in pred_comp.items():
                if isinstance(comp, dict) and "predictors" in comp:
                    gnn_data = comp["predictors"].get("GNN", {})
                    mlp_data = comp["predictors"].get("MLP", {})
                    gnn_mean = gnn_data.get("mean_de_gap", {})
                    mlp_mean = mlp_data.get("mean_de_gap", {})
                    if isinstance(gnn_mean, dict):
                        mean_de_gap = gnn_mean.get("mean", 0.0)
                    if isinstance(mlp_mean, dict) and isinstance(gnn_mean, dict):
                        g = gnn_mean.get("mean", 1e-10)
                        m = mlp_mean.get("mean", 0.0)
                        mlp_gnn_ratio = m / max(g, 1e-10)
                    break
            source_topos = ["triangular", "heavy_hex"]
            target_topos = ["triangular", "heavy_hex"]

        elif exp_type == "orchestrator_summary":
            verdict_info = data.get("verdict", {})
            verdict = verdict_info.get("overall", "")
            all_pass = verdict_info.get("all_completed", False)
            total_time = verdict_info.get("total_time_s", total_time)

        return CrossTopologyResult(
            source_file=str(path),
            folder=path.parent.name,
            experiment_type=exp_type,
            target_n=target_n,
            threshold=threshold,
            seeds=seeds,
            norm_type=norm_type,
            hidden_dim=hidden_dim,
            n_epochs=n_epochs,
            source_topologies=source_topos,
            target_topologies=target_topos,
            mean_de_gap=mean_de_gap,
            std_de_gap=std_de_gap,
            max_de_gap=max_de_gap,
            pass_rate=pass_rate,
            n_pass=n_pass,
            n_total=n_total,
            verdict=verdict,
            all_pass=all_pass,
            graph_structure_essential=graph_essential,
            mlp_gnn_ratio=mlp_gnn_ratio,
            best_norm_type=best_norm,
            directions=directions,
            total_time_s=total_time,
            git_commit=git_commit,
            timestamp=timestamp,
        )

    # ── Recursive folder scanning ────────────────────────────────────────

    def _scan_folder_recursive(
        self,
        root: Path,
        noiseless: list[NoiselessResult],
        noisy: list[NoisyResult],
        *,
        parent_context: str = "",
    ) -> None:
        """Recursively scan a directory for pipeline and noisy results.

        Parameters
        ----------
        root : Path
            Directory to scan.
        noiseless : list
            Accumulator for noiseless results (mutated in place).
        noisy : list
            Accumulator for noisy results (mutated in place).
        parent_context : str
            Topology inferred from parent folder name (used as fallback).

        Fix #4: Now parses ALL pipeline_run files (not just the latest).
        """
        # Direct files in this folder — parse ALL (Fix #4)
        for pf in sorted(root.glob("pipeline_run_*.json")):
            result = self._parse_pipeline_file(pf, root.name)
            if result:
                _apply_topology_fallback(result, parent_context)
                noiseless.append(result)

        for nf in sorted(root.glob("noisy_*.json")):
            result = self._parse_noisy_file(nf, root.name)
            if result:
                _apply_topology_fallback(result, parent_context)
                noisy.append(result)

        # Recurse into subfolders
        for subfolder in sorted(root.iterdir()):
            if not subfolder.is_dir():
                continue
            # Skip hidden dirs and known non-result dirs
            if subfolder.name.startswith(".") or subfolder.name in _SKIP_FOLDERS:
                continue

            # Parse ALL pipeline_run files in subfolder (Fix #4)
            for pf in sorted(subfolder.glob("pipeline_run_*.json")):
                result = self._parse_pipeline_file(pf, subfolder.name)
                if result:
                    _apply_topology_fallback(result, parent_context)
                    noiseless.append(result)

            for nf in sorted(subfolder.glob("noisy_*.json")):
                result = self._parse_noisy_file(nf, subfolder.name)
                if result:
                    _apply_topology_fallback(result, parent_context)
                    noisy.append(result)

    # ── File parsers ─────────────────────────────────────────────────────

    def _parse_pipeline_file(self, path: Path, folder: str) -> NoiselessResult | None:
        """Parse a pipeline_run_*.json into a NoiselessResult.

        Fix #1: Reports worst-case ΔE/gap across ALL phase4_results entries.
        Previously only read phase4[0], which hid failures at other h_test values.

        Enhanced (2026-06-07): Extracts Phase 1/2/3/4 diagnostic fields that were
        previously ignored — gap_min, per-h VQE stats, theta_x_mse, energy
        decomposition, CES correlation, classification confidence, timestamps.
        """
        data = _load_json(path)
        if not data:
            return None

        config = data.get("config", {})
        mpnn_cfg = config.get("mpnn", {})
        system = data.get("system", {})
        diagnostics = data.get("diagnostics", {})
        phase4 = data.get("phase4_results", [])

        # Phase 4 primary metric — use worst-case across all test points (Fix #1)
        delta_e = None
        phase_label = ""
        phase_correct = None
        mag_x_error = None
        corr_zz_error = None

        if phase4:
            # Find the worst (highest) ΔE/gap across all test points
            worst_idx = 0
            worst_de = phase4[0].get("delta_e_over_gap")
            for i, entry in enumerate(phase4):
                de = entry.get("delta_e_over_gap")
                if de is not None and (worst_de is None or de > worst_de):
                    worst_de = de
                    worst_idx = i

            # Report the worst-case point as the primary metric
            p4 = phase4[worst_idx]
            delta_e = p4.get("delta_e_over_gap")
            phase_label = p4.get("phase_label", "")
            checklist = p4.get("metrics_checklist", {})
            phase_correct = checklist.get("correct_phase")
            mag_x_error = p4.get("mag_x_error")
            corr_zz_error = p4.get("corr_zz_error")

        # Phase diagnostics extraction
        phase1_diag = diagnostics.get("phase1", {})
        phase2_diag = diagnostics.get("phase2", {})
        phase3_diag = diagnostics.get("phase3", {})
        phase4_diag = diagnostics.get("phase4", {})

        # Extract p_layers with warning (Fix #2)
        p_layers = _extract_p_layers(config, system, path)

        # Extract model type and model-specific params
        model_type = config.get("model") or system.get("model", "tfim")
        model_params = {}
        if "g_longitudinal" in system or "g_longitudinal" in config:
            g_val = system.get("g_longitudinal") or config.get("g_longitudinal", 0.0)
            if g_val:
                model_params["g"] = g_val

        # Phase 2: compute mean iterations and max restart spread
        per_h_iters = phase2_diag.get("per_h_iterations", [])
        mean_iterations = sum(per_h_iters) / len(per_h_iters) if per_h_iters else None
        per_h_spread = phase2_diag.get("per_h_restart_spread", [])
        max_restart_spread = max(per_h_spread) if per_h_spread else None

        # Phase 4 diagnostics: energy decomposition, CES correlation, confidence
        energy_decomp = phase4_diag.get("energy_decomposition") or {}
        error_from_circuit = energy_decomp.get("error_from_circuit")
        error_from_mpnn = energy_decomp.get("error_from_mpnn")

        # Extract run timestamp from filename (pipeline_run_YYYYMMDD_HHMMSS.json)
        run_timestamp = _extract_timestamp_from_filename(path.name)

        # Derive regime from h_test (worst-case h → hardest regime)
        _h_test_vals = config.get("h_test", [])
        _j_val = float(config.get("J", system.get("J", 1.0)))
        if _h_test_vals:
            # Classify by the minimum h in h_test (hardest regime dominates)
            _regime = classify_regime(min(_h_test_vals), _j_val)
        elif config.get("h_values"):
            _regime = classify_regime(min(config["h_values"]), _j_val)
        else:
            _regime = ""

        return NoiselessResult(
            source_file=str(path),
            folder=folder,
            n_qubits=_get_int(config, "n_qubits") or _get_int(system, "n_qubits"),
            p_layers=p_layers,
            topology=config.get("topology") or system.get("topology", ""),
            n_restarts=config.get("n_restarts", 5),
            seed=config.get("seed"),
            model=model_type,
            model_params=model_params,
            h_values=config.get("h_values", []),
            h_test=config.get("h_test", []),
            hidden_dim=mpnn_cfg.get("hidden_dim", 128),
            n_epochs=mpnn_cfg.get("n_epochs", 6000),
            patience=mpnn_cfg.get("patience", 500),
            # Phase 1
            gap_min=phase1_diag.get("gap_min"),
            phase1_elapsed_s=phase1_diag.get("elapsed_s", 0.0),
            # Phase 4 primary
            delta_e_over_gap=delta_e,
            phase_label=phase_label,
            phase_correct=phase_correct,
            mag_x_error=mag_x_error,
            corr_zz_error=corr_zz_error,
            # Phase 2
            convergence_rate=phase2_diag.get("convergence_rate"),
            theta_smoothness=phase2_diag.get("theta_smoothness"),
            worst_convergence_h=phase2_diag.get("worst_convergence_h"),
            mean_iterations=mean_iterations,
            max_restart_spread=max_restart_spread,
            phase2_elapsed_s=phase2_diag.get("total_elapsed_s", 0.0),
            # Phase 3
            generalization_gap=phase3_diag.get("generalization_gap"),
            theta_zz_mse=phase3_diag.get("theta_zz_mse"),
            theta_x_mse=phase3_diag.get("theta_x_mse"),
            phase3_elapsed_s=phase3_diag.get("elapsed_s", 0.0),
            # Phase 4 diagnostics
            error_from_circuit=error_from_circuit,
            error_from_mpnn=error_from_mpnn,
            ces_energy_r=phase4_diag.get("ces_energy_pearson_r"),
            classification_confidence=phase4_diag.get("classification_confidence"),
            # Timing
            elapsed_s=data.get("elapsed_s", 0),
            run_timestamp=run_timestamp,
            variant_id=folder,
            # Regime
            regime=_regime,
        )

    def _parse_noisy_file(self, path: Path, folder: str) -> NoisyResult | None:
        """Parse a noisy_*.json into a NoisyResult."""
        data = _load_json(path)
        if not data:
            return None

        config = data.get("config", {})
        system = data.get("system", {})
        summary = data.get("summary", {})
        per_h = data.get("results_per_h", [])

        # Extract p_layers with warning (Fix #2)
        p_layers = _extract_p_layers(config, system, path)

        # Detect ZNE strategy from config or filename
        zne_strategy = config.get("zne_strategy", "") or config.get("amplifier", "")
        if not zne_strategy:
            fname_lower = path.name.lower()
            if "pea" in fname_lower:
                zne_strategy = "pea"
            elif "gf" in fname_lower or "gate_folding" in fname_lower:
                zne_strategy = "gate_folding"
            elif "ces" in fname_lower:
                zne_strategy = "ces"

        return NoisyResult(
            source_file=str(path),
            folder=folder,
            n_qubits=_get_int(config, "n_qubits") or _get_int(system, "n_qubits"),
            p_layers=p_layers,
            topology=config.get("topology") or system.get("topology", ""),
            seed=config.get("seed", 42),
            n_layouts=config.get("n_layouts", 3),
            shots=config.get("shots", 16384),
            h_values=config.get("h_values", []),
            zne_strategy=zne_strategy,
            mean_r2=summary.get("mean_r2", 0),
            mean_gain_pct=summary.get("mean_gain_pct", 0),
            n_mitigated_wins=summary.get("n_mitigated_wins", 0),
            n_total=summary.get("n_total", 0),
            success_criteria_met=summary.get("success_criteria_met", False),
            mean_de_noiseless=summary.get("mean_de_noiseless", 0),
            mean_de_noisy_raw=summary.get("mean_de_noisy_raw", 0),
            mean_de_zne=summary.get("mean_de_zne", 0),
            per_h_r2=[p.get("r_squared", 0) for p in per_h],
            per_h_gain=[p.get("gain_pct", 0) for p in per_h],
            elapsed_s=summary.get("elapsed_s", 0),
            variant_id=folder,
        )

    def _parse_experiment_dir(self, exp_dir: Path) -> ExperimentResult | None:
        """Parse an experiment directory (exp_<id>/) into ExperimentResult.

        Handles both BaseExperiment and ValidationRunner result formats:
        - BaseExperiment: data["analysis"]["summary"] with mean_de_gap, pass_rate
        - ValidationRunner: data["summary"] with n_passed, pass_rate, hypotheses

        Uses recursive glob to support nested directory structures
        (e.g., exp_noiseless/tfim/heavy_hex/run_*.json).
        """
        run_files = sorted(exp_dir.rglob("run_*.json"), reverse=True)
        if not run_files:
            return None

        data = _load_json(run_files[0])
        if not data:
            return None

        config = data.get("config", {})
        analysis = data.get("analysis", {})
        summary = analysis.get("summary", {})
        system = config.get("system", {})

        # ValidationRunner format: summary at top level with pass_rate
        # (the _build_envelope also mirrors it into analysis.summary)
        if not summary and "summary" in data:
            summary = data["summary"]
            # Build a compatible analysis dict
            if not analysis:
                analysis = {"summary": summary, "n_seeds": len(config.get("seeds", []))}

        if not summary or "error" in summary:
            # Try to synthesize a summary from analysis-level data
            # (covers E4b, S8, S8b which use non-standard formats)
            synthesized = _synthesize_summary_from_analysis(analysis, data)
            if synthesized:
                summary = synthesized
            else:
                return None

        exp_id = config.get("experiment_id", exp_dir.name.replace("exp_", "").upper())

        # Safe category extraction (handles multi-word IDs like "MPS_HW")
        category = config.get("category", "")
        if not category and exp_id:
            category = exp_id[0] if len(exp_id) > 0 else ""

        # Compute verdict using centralized criteria
        verdict, criteria_desc = compute_verdict(exp_id, summary)

        # ValidationRunner: extract hypotheses info for richer reporting
        extras: dict[str, Any] = {}
        hypotheses = summary.get("hypotheses") or data.get("summary", {}).get("hypotheses")
        if hypotheses:
            extras["hypotheses"] = hypotheses
            extras["n_hypotheses"] = len(hypotheses)
            extras["n_confirmed"] = sum(1 for v in hypotheses.values() if v)
            # Override verdict based on hypotheses if compute_verdict gives generic result
            if all(hypotheses.values()):
                verdict = "confirmed"
                criteria_desc = (
                    f"{extras['n_confirmed']}/{extras['n_hypotheses']} hypotheses confirmed"
                )
            elif any(hypotheses.values()):
                verdict = "confirmed"
                criteria_desc = (
                    f"{extras['n_confirmed']}/{extras['n_hypotheses']} hypotheses confirmed "
                    f"(partial)"
                )

        # ValidationRunner: extract per-section summary
        results_data = data.get("results", {})
        if results_data and any(k.startswith("section_") for k in results_data):
            sections_info = []
            for k in sorted(results_data.keys()):
                if k.startswith("section_"):
                    sec = results_data[k]
                    sections_info.append(
                        {
                            "name": sec.get("name", k),
                            "success": sec.get("success"),
                            "elapsed_s": sec.get("elapsed_s", 0),
                        }
                    )
            extras["sections"] = sections_info

        # Experiment-specific extras (legacy)
        if exp_id == "A3":
            extras["scaling_law_fit"] = analysis.get("scaling_law_fit", {})
        elif exp_id == "G1":
            extras["data_efficiency"] = analysis.get("data_efficiency", {})

        # Extract p_layers
        p_layers_val = system.get("p_layers") or config.get("p_layers")
        p_layers = int(p_layers_val) if p_layers_val is not None else 2

        # Extract model type
        model_type = system.get("model") or config.get("model", "tfim")

        return ExperimentResult(
            source_file=str(run_files[0]),
            folder=exp_dir.name,
            experiment_id=exp_id,
            category=category,
            hypothesis=config.get("hypothesis", ""),
            description=config.get("description", ""),
            n_qubits=system.get("n_qubits", 0),
            p_layers=p_layers,
            topology=system.get("topology", ""),
            model=model_type,
            h_values=system.get("h_values", []),
            seeds=config.get("seeds", []),
            verdict=verdict,
            criteria=criteria_desc,
            mean_de_gap=summary.get("mean_de_gap"),
            std_de_gap=summary.get("std_de_gap"),
            pass_rate=summary.get("pass_rate"),
            n_seeds=analysis.get("n_seeds", len(config.get("seeds", []))),
            total_time_s=summary.get("total_time_s") or summary.get("total_elapsed_s", 0),
            extras=extras,
        )


# ═══════════════════════════════════════════════════════════════════════════
# Utilities
# ═══════════════════════════════════════════════════════════════════════════


def _synthesize_summary_from_analysis(
    analysis: dict[str, Any], data: dict[str, Any]
) -> dict[str, Any] | None:
    """Synthesize a standard summary dict from non-standard analysis formats.

    Handles experiments that store results in custom analysis structures
    (E4b: hypothesis_confirmed + per_g_stats, S8/S8b: custom fitting results)
    without a standard `summary` dict.

    Returns a summary dict with at least `pass_rate`, or None if no usable data.
    """
    # Pattern 1: hypothesis_confirmed in analysis (E4b-style)
    if "hypothesis_confirmed" in analysis:
        confirmed = analysis["hypothesis_confirmed"]
        return {
            "pass_rate": 1.0 if confirmed else 0.0,
            "hypothesis_confirmed": confirmed,
        }

    # Pattern 2: S8/S8b-style with fitting results
    if "nu_median" in analysis or "h_peaks_per_N" in analysis:
        # S8 uses nu fitting — confirmed if consistent peaks found
        confirmed = analysis.get("hypothesis_confirmed", False)
        n_fits = analysis.get("n_successful_fits", 0)
        n_seeds = analysis.get("n_seeds", 1)
        return {
            "pass_rate": n_fits / max(n_seeds, 1),
            "hypothesis_confirmed": confirmed,
        }

    # Pattern 3: results dict has per-seed data (E4b with seeds as keys)
    results = data.get("results", {})
    if results and all(k.isdigit() for k in results):
        # Per-seed results — count successes
        n_total = len(results)
        if n_total > 0:
            return {"pass_rate": 1.0, "n_seeds": n_total}

    return None


def _load_json(path: Path) -> dict[str, Any] | None:
    """Safely load a JSON file, returning None on failure.

    Delegates to the canonical load_result from framework.result_io for
    consistent error handling (size guard, corruption detection).
    """
    try:
        from qmbp_simulation.framework.result_io import load_result
        return load_result(path)
    except (FileNotFoundError, ValueError) as e:
        logger.debug("Failed to load %s: %s", path, e)
        return None
    except (OSError, UnicodeDecodeError) as e:
        logger.debug("Failed to load %s: %s", path, e)
        return None


def _get_int(d: dict, key: str) -> int:
    """Get an integer from a dict, returning 0 for None/missing."""
    val = d.get(key)
    return int(val) if val is not None else 0


def _extract_p_layers(config: dict, system: dict, path: Path) -> int:
    """Extract p_layers from config/system dicts.

    Fix #2: Logs a warning instead of silently defaulting to 2.
    Still returns 2 as default (for backward compat with NoiselessResult dataclass),
    but the warning makes it visible in --verbose mode.
    """
    p = config.get("p_layers") or system.get("p_layers")
    if p is not None:
        return int(p)
    logger.warning("p_layers not found in %s; defaulting to 2", path.name)
    return 2


def _infer_topology_from_name(name: str) -> str:
    """Infer topology from a folder name (e.g., 'variants_N10_ladder' → 'ladder')."""
    name_lower = name.lower()
    for topo in _KNOWN_TOPOLOGIES:
        if topo in name_lower:
            # Normalize the typo
            return "chain_1d" if topo == "linnear" else topo
    return ""


def _apply_topology_fallback(result: NoiselessResult | NoisyResult, context: str) -> None:
    """Set topology from parent context if the result file didn't specify one."""
    if not result.topology and context:
        result.topology = context


def _extract_timestamp_from_filename(filename: str) -> str:
    """Extract ISO timestamp from pipeline_run_YYYYMMDD_HHMMSS.json filename.

    Returns empty string if the pattern doesn't match (legacy files).
    """
    import re

    match = re.search(r"(\d{8})_(\d{6})", filename)
    if not match:
        return ""
    date_str, time_str = match.group(1), match.group(2)
    try:
        # Convert to ISO format: YYYY-MM-DDTHH:MM:SS
        return (
            f"{date_str[:4]}-{date_str[4:6]}-{date_str[6:8]}"
            f"T{time_str[:2]}:{time_str[2:4]}:{time_str[4:6]}"
        )
    except (IndexError, ValueError):
        return ""
