#!/usr/bin/env python3
"""Auto-generate analysis report from ResultIndex data.

Produces a markdown report with coverage matrix, best results per config,
recent regressions, and suggested next experiments. Intended as a complement
to the manually-curated noiseless_v2_analysis.md.

Usage:
    python scripts/generate_analysis_report.py
    python scripts/generate_analysis_report.py --output documentation/analysis/auto_report.md
"""

from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from qmbp_simulation.framework.result_index import ResultIndex


def generate_report(index: ResultIndex) -> str:
    """Generate markdown analysis report from the index."""
    stats = index.stats()
    matrix = index.coverage_matrix()
    regressions = index.detect_regressions()
    suggestions = index.suggest_next()

    lines = [
        "# Experiment Results — Auto-Generated Report",
        "",
        f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"**Indexed runs**: {stats.get('total_runs', 0)}",
        f"**Pass rate**: {stats.get('n_passed', 0)}/{stats.get('total_runs', 0)} "
        f"({stats.get('pass_rate', 0):.0%})",
        f"**Compute time**: {stats.get('total_compute_hours', 0):.1f}h",
        "",
        "---",
        "",
        "## Coverage Matrix",
        "",
        "Best pass_rate achieved per (model, topology) combination.",
        "",
    ]

    # Coverage table
    if matrix:
        models = sorted(matrix.keys())
        topos = sorted(set(t for m in matrix.values() for t in m.keys()))
        lines.append("| Model | " + " | ".join(topos) + " |")
        lines.append("|" + "---|" * (len(topos) + 1))
        for model in models:
            row = f"| {model} |"
            for topo in topos:
                val = matrix.get(model, {}).get(topo, "—")
                row += f" {val} |"
            lines.append(row)
        lines.append("")

    # Best results table
    lines.append("## Best Results (100% pass)")
    lines.append("")
    perfect = index.query(passed=True)
    if perfect:
        # Group by model+topology, show largest N
        from collections import defaultdict
        best_n: dict[tuple, dict] = defaultdict(lambda: {"n": 0})
        for r in perfect:
            key = (r.get("model", ""), r.get("topology", ""))
            if r.get("n_qubits", 0) > best_n[key]["n"]:
                best_n[key] = {"n": r["n_qubits"], "p": r.get("p_layers"), "file": r.get("_file", "")}
        lines.append("| Model | Topology | Max N | p | File |")
        lines.append("|---|---|:---:|:---:|---|")
        for (model, topo), info in sorted(best_n.items()):
            if info["n"] > 0:
                lines.append(f"| {model} | {topo} | {info['n']} | {info['p']} | `{info['file']}` |")
        lines.append("")

    # Regressions
    if regressions:
        lines.append("## ⚠️ Regressions")
        lines.append("")
        for r in regressions[:10]:
            lines.append(
                f"- **{r['config']}**: latest={r['latest_pass_rate']:.0%} "
                f"vs best={r['best_previous_pass_rate']:.0%} (Δ={r['delta']:.0%})"
            )
        lines.append("")

    # Suggestions
    if suggestions:
        lines.append("## Suggested Next")
        lines.append("")
        for s in suggestions:
            lines.append(f"- {s}")
        lines.append("")

    lines.append("---")
    lines.append("*Auto-generated by `scripts/generate_analysis_report.py`*")
    return "\n".join(lines)


def main() -> int:
    import argparse
    parser = argparse.ArgumentParser(description="Generate analysis report from index.")
    parser.add_argument("--output", "-o", type=str, default="documentation/analysis/auto_report.md")
    parser.add_argument("--rebuild-index", action="store_true", help="Force index rebuild first")
    args = parser.parse_args()

    index = ResultIndex()
    if args.rebuild_index or len(index) == 0:
        index.rebuild()

    report = generate_report(index)
    output_path = ROOT / args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report)
    print(f"Report generated: {output_path} ({len(report)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
